EXE = main
TEST = test

EXE_OBJ = main.o
OBJS = main.o Node.o covidgraph.o covidgraph-getter.o dsets.o Image.o visualization.o Animation.o

# Use the CS 225 Makefile template
include cs225/make/cs225.mk